-- MySQL Script generated by MySQL Workbench
-- Mon Aug 12 11:33:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Instruments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Instruments` (
  `instrumentName` VARCHAR(20) NOT NULL,
  `hashedValue` INT NULL,
  `isNegative` TINYINT(1) NULL,
  `basePrice` FLOAT NULL,
  `drift` FLOAT NULL,
  `variance` FLOAT NULL,
  PRIMARY KEY (`instrumentName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Deals` (
  `dealId` INT NOT NULL,
  `instrumentName` VARCHAR(20) NULL,
  `cpty` VARCHAR(20) NULL,
  `price` FLOAT NULL,
  `type` CHAR(1) NULL,
  `quantity` INT NULL,
  `time` DATETIME(5) NULL,
  PRIMARY KEY (`dealId`)),
  FOREIGN KEY(instrumentName) REFERENCES `mydb`.`Instruments`(`instrumentName`));
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
